### PR TITLE
options.PouchDB

### LINKED ISSUE #104: options.PouchDB
We want the Hoodie Client to not only run in browsers, but also on servers (server-side rendering) and in Service Workers. We are currently [removing `@hoodie/client-store`'s dependency on `PouchDB`](https://github.com/hoodiehq/hoodie-store-client/issues/134) by replacing it with `options.PouchDB`

This will also give developers more control about the used PouchDB version and [custom build](https://pouchdb.com/custom.html). Only `hoodie` should have a dependency on PouchDB, all lower-level dependencies should work with options.

Pull request: #107

### PR DESCRIPTION
**Pull request by gr2m**
closes #104

### CODE REVIEW

**Comment by Charlotteis** [comment]
😎

**Comment by gr2m** [comment]
ooopsie you were way to fast I forgot to add my WIP notice :D no problem, totally my fault, I got this

**Comment by Charlotteis** [comment]
@gr2m aaaaah! Very sorry. :)

**Comment by gr2m** [comment]
this will teach me a lesson 👍

**Comment by gr2m** [comment]
follow up: https://github.com/hoodiehq/hoodie-client/pull/107

**Pull request merged**
