### PR TITLE
cross-module initialisations

### LINKED ISSUE #3: init account/store/task APIs
- [x] if username is set, start syncing store, compare https://github.com/hoodiehq/hoodie/blob/hoodie-client-legacy/src/hoodie.js#L68-L69
- [x] start checking if connected to server, compare https://github.com/hoodiehq/hoodie/blob/hoodie-client-legacy/src/hoodie/connection.js
- [x] on account signup/signin/changeusername/reauthenticated, start syncing store
- [x] on account signout, clear hoodie store
- [x] on account signout, reset task connection

That should :tm: be it

### PR DESCRIPTION
**Pull request by gr2m**
fixes  #3

there are several things that need to be initialised in Hoodie’s client constructor, where we combine account, store etc APIs. They are all listed here: #3.

### CODE REVIEW

**Comment by gr2m** [comment]
with the latest commit: https://github.com/hoodiehq/hoodie-client/pull/63/commits/ebc304ede8515e00beb973f5c3cc48ed9e41aa1d this should be good to go. Now needs tests

**Comment by gr2m** [comment]
This is good for review @hoodiehq/maintainers. Together with https://github.com/hoodiehq/hoodie-store-client/pull/97, this will fix several crucial issue the Hoodie Tent Version has today. 

Ignore the decrease in coveralls, we don’t have 100% code coverage anyway at this point.

**Comment by HipsterBrown** [comment]
Makes sense to me. The variable names are great and very clear. I'm really enjoying the use of `hooks` as well. :+1: LGTM

**Comment by gr2m** [comment]
thanks for the review :)

**Pull request merged**
