### PR TITLE
Update get-api.js for pouchDB V7

### PR DESCRIPTION
**Pull request by PiTomar**
Add compatibility for pouchDB V7
See discussion in https://github.com/hoodiehq/hoodie/issues/888

### CODE REVIEW

**Comment by gr2m** [comment]
ping @Terreii could you give that a try?

**Comment by Terreii** [comment]
Works on my machine 😁

https://github.com/Terreii/hoodie-client-test

**Review by gr2m — APPROVED** [review]
here goes nothing :)

**Comment by gr2m** [comment]
published in https://github.com/hoodiehq/hoodie-client/releases/tag/v10.2.0

**Pull request merged**
